# Generated by Django 5.2.2 on 2025-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='default-phone', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
