# Generated by Django 5.2.2 on 2025-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('owner', 'Shop/Enterprise Owner'), ('normal', 'Normal User')], max_length=20, null=True, verbose_name='User Type'),
        ),
    ]
