# Generated by Django 5.2.2 on 2025-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_profile_city_profile_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
    ]
