# Generated by Django 5.2.2 on 2025-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
