# Generated by Django 5.2.2 on 2025-06-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_profile_total_rating_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
