# Generated by Django 5.2.2 on 2025-06-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_profile_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_rating',
            field=models.IntegerField(default=1),
        ),
    ]
