# Generated by Django 5.2.2 on 2025-06-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_profile_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
