# Generated by Django 5.2.2 on 2025-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_profile_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='nill'),
            preserve_default=False,
        ),
    ]
