# Generated by Django 5.2.2 on 2025-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_profile_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
