# Generated by Django 5.2.2 on 2025-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_profile_total_rating_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
