# Generated by Django 5.2.2 on 2025-06-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_profile_facebook_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='website_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='whatsapp',
            new_name='whatsapp_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='youtube',
            new_name='youtube_link',
        ),
    ]
