# Generated by Django 5.2.2 on 2025-06-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_customuser_from_telegram_customuser_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
